// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // `prisma generate` in CI only needs a syntactically valid URL to generate the client.
    // Runtime DB access is still enforced by backend/src/lib/prisma.ts.
    url: process.env["DATABASE_URL"] ?? "postgresql://postgres:postgres@localhost:5432/localsupply",
  },
});
