// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Use || instead of ?? so empty strings from unset CI secrets fall through.
    url:
      process.env["DATABASE_URL"] ||
      process.env["POSTGRES_URL"] ||
      process.env["POSTGRES_PRISMA_URL"] ||
      "postgresql://postgres:postgres@localhost:5432/localsupply",
  },
});
